insert into [dbo].[genre] (name) values ('Drama');
insert into [dbo].[genre] (name) values ('Horror');
insert into [dbo].[genre] (name) values ('Musical');
insert into [dbo].[genre] (name) values ('Comedy');
insert into [dbo].[genre] (name) values ('Children');
insert into [dbo].[genre] (name) values ('Western');
insert into [dbo].[genre] (name) values ('Romance');
insert into [dbo].[genre] (name) values ('Thriller');
insert into [dbo].[genre] (name) values ('Mystery');
insert into [dbo].[genre] (name) values ('Crime');
insert into [dbo].[genre] (name) values ('Documentary');
insert into [dbo].[genre] (name) values ('Sci-Fi');
insert into [dbo].[genre] (name) values ('Fantasy');
insert into [dbo].[genre] (name) values ('War');
insert into [dbo].[genre] (name) values ('Film-Noir');
insert into [dbo].[genre] (name) values ('IMAX');
insert into [dbo].[genre] (name) values ('Action');
insert into [dbo].[genre] (name) values ('Animation');
insert into [dbo].[genre] (name) values ('Adventure');
INSERT INTO [dbo].[genre] (name) VALUES ('History');
INSERT INTO [dbo].[genre] (name) VALUES ('Science Fiction');
INSERT INTO [dbo].[genre] (name) VALUES ('TV Movie');
