INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Abyss', N'11 years ago, inspector Malik couldn’t solve a kidnapping case and a little girl died. Now with only a few days before the crime gets classified, he decides to reopen the case. Malik owes it to the mother and to himself. As he digs into the past, a child is kidnapped again. The pattern is the same one as a decade ago, it’s no coincidence. Malik knows he has a few days to make things right and to bring justice.', '2024-12-11', 51, 3.0, 'https://image.tmdb.org/t/p/w500/foyiQu23zq4WhmffnQkFiNAvqcJ.jpg', 4.5, 95);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Afterburn', N'Set against the backdrop of a postapocalyptic Earth whose Eastern Hemisphere was destroyed by a massive solar flare, leaving what life remains mutated from radiation and fallout. The story revolves around a group of treasure hunters who extract such objects as the Mona Lisa, the Rosetta Stone and the Crown Jewels while facing rival hunters, mutants and pirates.', '2025-08-20', 97, 3.4, 'https://image.tmdb.org/t/p/w500/xR0IhVBjbNU34b8erhJCgRbjXo3.jpg', 5.1, 105);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'War of the Worlds', N'Will Radford is a top analyst for Homeland Security who tracks potential threats through a mass surveillance program, until one day an attack by an unknown entity leads him to question whether the government is hiding something from him... and from the rest of the world.', '2025-07-29', 684, 2.1, 'https://image.tmdb.org/t/p/w500/yvirUYrva23IudARHn3mMGVxWqM.jpg', 3.15, 91);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Black Phone 2', N'Four years after escaping The Grabber, Finney Blake is struggling with his life after captivity. When his sister Gwen begins receiving calls in her dreams from the black phone and seeing disturbing visions of three boys being stalked at a winter camp, the siblings become determined to solve the mystery and confront a killer who has grown more powerful in death and more significant to them than either could imagine.', '2025-10-15', 195, 3.5, 'https://image.tmdb.org/t/p/w500/xUWUODKPIilQoFUzjHM6wKJkP3Y.jpg', 5.25, 114);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Chainsaw Man - The Movie: Reze Arc', N'In a brutal war between devils, hunters, and secret enemies, a mysterious girl named Reze has stepped into Denji''s world, and he faces his deadliest battle yet, fueled by love in a world where survival knows no rules.', '2025-09-19', 132, 4.1, 'https://image.tmdb.org/t/p/w500/xdzLBZjCVSEsic7m7nJc4jNJZVW.jpg', 6.15, 100);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Martin', N'Martin revolves around Lt. Brigadier Arjun Saxena, whose journey takes him from Pakistan to India to discover his real identity and fight against black market dealers, who are involved with terrorists to orchestrate massive attacks in the country.', '2024-10-11', 19, 1.9, 'https://image.tmdb.org/t/p/w500/bYe2ZjUhb4Kje0BpWE6kN34u2hv.jpg', 2.85, 147);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Captain Hook - The Cursed Tides', N'In the aftermath of a devastating defeat by his archnemesis Admiral Smee, the notorious Captain James Hook finds refuge in the coastal town of Eldritch Landing, where he forms an unlikely alliance with Silas Blackweather, a local blacksmith seeking retribution for his sister''s murder. As they evade Smee''s Redcoat Soldiers in the island''s dense woodland, ruthless sword fights, ancient curses and conflicting motives will challenge their shared quest for revenge. Together, Hook and Silas navigate uncharted waters to confront the treacherous Admiral Smee, embarking on a journey that will redefine Captain Hook''s enduring legacy.', '2025-07-11', 34, 2.5, 'https://image.tmdb.org/t/p/w500/bcP7FtskwsNp1ikpMQJzDPjofP5.jpg', 3.75, 90);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Demon Slayer: Kimetsu no Yaiba Infinity Castle', N'The Demon Slayer Corps are drawn into the Infinity Castle, where Tanjiro, Nezuko, and the Hashira face terrifying Upper Rank demons in a desperate fight as the final battle against Muzan Kibutsuji begins.', '2025-07-18', 508, 3.9, 'https://image.tmdb.org/t/p/w500/fWVSwgjpT2D78VUh6X8UBd2rorW.jpg', 5.85, 156);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Hunting Grounds', N'Desperate to find refuge for her children, Chloe Marvino runs away from her Mafia tied husband, and finds shelter in a cabin with a recluse drifter named Jake. But as her husband''s henchmen draw closer to her, it turns out that Jake is the biggest enemy of them all.', '2025-05-16', 52, 3.4, 'https://image.tmdb.org/t/p/w500/cgZjpqRQt9sk6XMCwZ3B1NPAaoy.jpg', 5.1, 89);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Ugly Stepsister', N'In a fairy-tale kingdom where beauty is a brutal business, Elvira battles to compete with her incredibly beautiful stepsister, and she will go to any length to catch the prince’s eye.', '2025-03-07', 593, 3.7, 'https://image.tmdb.org/t/p/w500/rayAREIKtSinuov10GvrZHyXfXH.jpg', 5.55, 109);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Stolen Girl', N'In 1993, Maureen’s six-year-old daughter Amina is snuck out of the country by her ex-husband, Karim. After years of unsuccessful attempts to find her, Maureen intersects with a professional retriever of internationally abducted children who promises to help her find Amina in exchange for her collaboration.', '2025-09-04', 63, 3.3, 'https://image.tmdb.org/t/p/w500/fZlNXEHZsBp7unqw009MeBbMv87.jpg', 4.95, 110); 
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Our Fault', N'Jenna and Lion''s wedding brings about the long-awaited reunion between Noah and Nick after their breakup. Nick''s inability to forgive Noah stands as an insurmountable barrier. He, heir to his grandfather''s businesses, and she, starting her professional life, resist fueling a flame that''s still alive. But now that their paths have crossed again, will love be stronger than resentment?', '2025-10-15', 466, 3.8, 'https://image.tmdb.org/t/p/w500/yzqHt4m1SeY9FbPrfZ0C2Hi9x1s.jpg', 5.7, 112);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Coco', N'Despite his family’s baffling generations-old ban on music, Miguel dreams of becoming an accomplished musician like his idol, Ernesto de la Cruz. Desperate to prove his talent, Miguel finds himself in the stunning and colorful Land of the Dead following a mysterious chain of events. Along the way, he meets charming trickster Hector, and together, they set off on an extraordinary journey to unlock the real story behind Miguel''s family history.', '2017-10-27', 20372, 4.1, 'https://image.tmdb.org/t/p/w500/6Ryitt95xrO8KXuqRGm1fUuNwqF.jpg', 6.15, 105);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Conjuring: Last Rites', N'Paranormal investigators Ed and Lorraine Warren take on one last terrifying case involving mysterious entities they must confront.', '2025-09-03', 1223, 3.5, 'https://image.tmdb.org/t/p/w500/7JzOmJ1fIU43I3gLHYsY8UzNzjG.jpg', 5.25, 136);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Jester 2', N'When teen magician Max crosses paths with the sinister Jester on Halloween night, she must outsmart a supernatural killer whose magic is all too real and whose tricks always end up in blood.', '2025-09-15', 27, 3.3, 'https://image.tmdb.org/t/p/w500/47dsw1jSOV0Be5zmy7CtLhYpqU.jpg', 4.95, 87);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'KPop Demon Hunters', N'When K-pop superstars Rumi, Mira and Zoey aren''t selling out stadiums, they''re using their secret powers to protect their fans from supernatural threats.', '2025-06-20', 1807, 4.1, 'https://image.tmdb.org/t/p/w500/zT7Lhw3BhJbMkRqm9Zlx2YGMsY0.jpg', 6.15, 96);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Inside Furioza', N'In the wake of murder, new Furioza leader Golden claims the reins of his violent and formidable hooligan gang and takes on a new focus across borders.', '2025-10-14', 58, 3.3, 'https://image.tmdb.org/t/p/w500/dbe1zKVKNBIczdmRcm7jxEphYLz.jpg', 4.95, 166);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'xXx', N'Xander Cage is your standard adrenaline junkie with no fear and a lousy attitude. When the US Government "recruits" him to go on a mission, he''s not exactly thrilled. His mission: to gather information on an organization that may just be planning the destruction of the world, led by the nihilistic Yorgi.', '2002-08-09', 4617, 3.0, 'https://image.tmdb.org/t/p/w500/xeEw3eLeSFmJgXZzmF2Efww0q3s.jpg', 4.5, 124);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'A House of Dynamite', N'When a single, unattributed missile is launched at the United States, a race begins to determine who is responsible and how to respond.', '2025-10-02', 577, 3.2, 'https://image.tmdb.org/t/p/w500/AiJ8L90ftPAwVf3SDx7Fj9IMZoy.jpg', 4.8, 112);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Toxic Avenger Unrated', N'When a downtrodden janitor, Winston Gooze, is exposed to a catastrophic toxic accident, he’s transformed into a new kind of hero: The Toxic Avenger. Now, Toxie must rise from outcast to savior, taking on ruthless corporate overlords and corrupt forces who threaten his son, his friends, and his community.', '2025-08-28', 170, 3.2, 'https://image.tmdb.org/t/p/w500/sIonGSpGNtH72OzbJllPOEMNjVU.jpg', 4.8, 102);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Long Walk', N'In a dystopian, alternate-America ruled by a totalitarian regime, 50 teenage boys take part in a deadly annual walking contest, forced to maintain a minimum pace or be executed, until only one survivor remains.', '2025-09-10', 646, 3.5, 'https://image.tmdb.org/t/p/w500/wobVTa99eW0ht6c1rNNzLkazPtR.jpg', 5.25, 108);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'People: A Musical Celebration', N'In how many wonderful ways are we different from each other'' What if the world were to rejoice in our differences'' Cara and her lovable Grandfather (Hume Cronyn) embark on a journey of imagination that brings them face to face with the wonderful variety of people around the world. Featuring 10 original songs by major recording artists, elaborate animation, and unforgettable characters.', '1995-01-01', 4, 3.1, 'https://image.tmdb.org/t/p/w500/lWcTir4r9bIAvp39aYzz0ZFhJef.jpg', 4.65, 49);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Beyond the Curtain', N'A British flight officer plans to rescue an airline stewardess who is trapped in East Germany.', '1960-04-01', 3, 3.0, 'https://image.tmdb.org/t/p/w500/o8Z0NGFxSmvXKuXYAQbvikC51M.jpg', 4.5, 88);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Predator: Badlands', N'Cast out from his clan, a young Predator finds an unlikely ally in a damaged android and embarks on a treacherous journey in search of the ultimate adversary.', '2025-11-05', 16, 3.0, 'https://image.tmdb.org/t/p/w500/ef2QSeBkrYhAdfsWGXmp0lvH0T1.jpg', 4.5, 107);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Three Jolly Fellows', N'Three Jolly Fellows tells of the adventures of three small men in a world that borders on the fantastic: the composed and close-to-nature Mossbeard, the irritable city dweller Halfshoe, and the sensitive poet Muff.', '1990-08-31', 3, 3.5, 'https://image.tmdb.org/t/p/w500/9UM0w5asK1Yjiy4KtQwHxHIUUZF.jpg', 5.25, 59);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Fantastic 4: First Steps', N'Against the vibrant backdrop of a 1960s-inspired, retro-futuristic world, Marvel''s First Family is forced to balance their roles as heroes with the strength of their family bond, while defending Earth from a ravenous space god called Galactus and his enigmatic Herald, Silver Surfer.', '2025-07-23', 2143, 3.6, 'https://image.tmdb.org/t/p/w500/cm8TNGBGG0aBfWj0LgrESHv8tir.jpg', 5.4, 115);      
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Mannequin', N'A stylist assistant investigates her sister''s death in a historic LA building, only to face a vengeful ghost of a serial killer who dismembered victims decades ago. She must escape before she''s next.', '2025-08-24', 10, 2.9, 'https://image.tmdb.org/t/p/w500/oFTpB1gzS02LtrsenTWxOKbsMpM.jpg', 4.35, 85);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Elixir', N'An elixir unleashes the undead in a village. A family at odds with one another must unite and fight to survive as their hometown collapses.', '2025-10-22', 112, 3.0, 'https://image.tmdb.org/t/p/w500/hQYEkXiAcgzQkr4aqLxWpNUFvN5.jpg', 4.5, 118);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Rats: A Witcher Tale', N'To pull off a daring heist, a gang of six misfit outlaws will have to do something they''ve never done before: trust each other — and a washed-up Witcher.', '2025-10-29', 43, 2.5, 'https://image.tmdb.org/t/p/w500/5Gr4amaB1xxeYAEMOdrVutaWwgz.jpg', 3.75, 83);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Ballad of a Small Player', N'Amid the glittering casinos of Macau, a gambler running from his past — and his debts — becomes fascinated by an enigmatic woman at the baccarat table.', '2025-10-15', 117, 3.0, 'https://image.tmdb.org/t/p/w500/yiXpXNiBWENaSJmdKfoT5DU0bL4.jpg', 4.5, 101);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Book', N'', '2024-11-08', 0, 0.0, 'https://image.tmdb.org/t/p/w500/bW5QfpXWbwhmP8o8mwgnJVCd2IL.jpg', 0.0, 0);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Drop', N'Bob Saginowski finds himself at the center of a robbery gone awry and entwined in an investigation that digs deep into the neighborhood''s past where friends, families, and foes all work together to make a living - no matter the cost.', '2014-09-12', 2312, 3.4, 'https://image.tmdb.org/t/p/w500/olQInYvVCW2wycMSU1ogo9Jshml.jpg', 5.1, 106);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Primitive War', N'During the Vietnam War, a recon unit ventures to an isolated jungle valley to uncover the fate of a missing platoon. They soon find themselves in a fight for their lives against an unexpected enemy — prehistoric dinosaurs.', '2025-08-21', 149, 3.4, 'https://image.tmdb.org/t/p/w500/nWBqU5YXmDVJWWEDJ4u3ZSseNVL.jpg', 5.1, 133);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Lost Princess', N'After an Ayahuasca vision transports him to a haunted castle, Alec meets Hanna who tales him the story of her mother''s forced marriage and how the forbidden passion with her father was in danger when the princess pregnancy became obvious', '2025-10-16', 33, 3.2, 'https://image.tmdb.org/t/p/w500/31S2ISsDtbnxb0kuXZl1SxSMD0K.jpg', 4.8, 105);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Holy Night: Demon Hunters', N'When a devil-worshipping criminal network plunges Seoul into chaos, the police turn to Holy Night—a trio of supernatural demon hunters—to restore order and defeat the rising evil.', '2025-04-30', 63, 3.3, 'https://image.tmdb.org/t/p/w500/v3Mo77Qjp6pctpD4eJaNT6kFRSB.jpg', 4.95, 92);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Hedda', N'Hedda Gabler finds herself torn between the lingering ache of a past love and the quiet suffocation of her present life. Over the course of one charged night, long-repressed desires and hidden tensions erupt—pulling her and everyone around her into a spiral of manipulation, passion, and betrayal.', '2025-10-22', 37, 2.5, 'https://image.tmdb.org/t/p/w500/ecflk7AZf0ij205yDswjlvdxlCO.jpg', 3.75, 107);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Weapons', N'When all but one child from the same class mysteriously vanish on the same night at exactly the same time, a community is left questioning who or what is behind their disappearance.', '2025-08-04', 2221, 3.7, 'https://image.tmdb.org/t/p/w500/cpf7vsRZ0MYRQcnLWteD5jK9ymT.jpg', 5.55, 128);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Dumb and Dumber To', N'20 years since their first adventure, Lloyd and Harry go on a road trip to find Harry''s newly discovered daughter, who was given up for adoption.', '2014-11-12', 3303, 2.8, 'https://image.tmdb.org/t/p/w500/cvEi0xV7TUkabJGuzulhvbMjrHi.jpg', 4.2, 110);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The People In The Walls', N'A viral ritual allows three kids to conjure people from the walls as they must now try to put them back before it is too late.', '2024-08-01', 6, 2.6, 'https://image.tmdb.org/t/p/w500/3NyL99rcDr5S4qQ8FXDwWiLujEE.jpg', 3.9, 93);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Lord of the Rings: The Fellowship of the Ring', N'Young hobbit Frodo Baggins, after inheriting a mysterious ring from his uncle Bilbo, must leave his home in order to keep it from falling into the hands of its evil creator. Along the way, a fellowship is formed to protect the ringbearer and make sure that the ring arrives at its final destination: Mt. Doom, the only place where it can be destroyed.', '2001-12-18', 26541, 4.2, 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg', 6.3, 179);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Marco', N'The adoptive son of the Adattu family, Marco, sets off on a ruthless quest for vengeance after his brother is brutally murdered, finding only betrayal, loss and unimaginable brutality at every step.', '2024-12-20', 81, 3.4, 'https://image.tmdb.org/t/p/w500/il3ao5gcF6fZNqo1o9o7lusmEyU.jpg', 5.1, 145);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Devil’s Trap', N'In the quiet nighttime corridors of a city hospital, Abigail (Nistratova) consoles her traumatized brother, Billy (Davi) who is now a paraplegic. Billy suffers from horrible nightmares in which he revisits his childhood, where we meet his alcoholic and violent father. Sharing Billy’s hospital room is a dying man, Mr. Cohen (Dern) who seems to know everything about Billy and Abigail. There’s also another horrific presence roaming in the hospital terrifying patients and staff alike.', '2024-11-01', 2, 2.0, 'https://image.tmdb.org/t/p/w500/deq8OGRj45eX1EFYQayG5T3Prar.jpg', 3.0, 90);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Forrest Gump', N'A man with a low IQ has accomplished great things in his life and been present during significant historic events—in each case, far exceeding what anyone imagined he could do. But despite all he has achieved, his one true love eludes him.', '1994-06-23', 28794, 4.2, 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg', 6.3, 142);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'My Fault', N'Noah must leave her city, boyfriend, and friends to move into William Leister''s mansion, the flashy and wealthy husband of her mother Rafaela. As a proud and independent 17 year old, Noah resists living in a mansion surrounded by luxury. However, it is there where she meets Nick, her new stepbrother, and the clash of their strong personalities becomes evident from the very beginning.', '2023-06-08', 3907, 3.9, 'https://image.tmdb.org/t/p/w500/w46Vw536HwNnEzOa7J24YH9DPRS.jpg', 5.85, 117);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Pirates of the Caribbean: At World''s End', N'Will Turner and Elizabeth Swann join forces with the revived Captain Barbossa to free Jack Sparrow from Davy Jones'' locker. The group must navigate dangerous waters, confront many foes and, ultimately, choose sides in a battle wherein piracy itself hangs in the balance.', '2007-05-19', 15002, 3.6, 'https://image.tmdb.org/t/p/w500/jGWpG4YhpQwVmjyHEGkxEkeRf0S.jpg', 5.4, 169);     
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Design Revolution', N'Four individuals from around the globe join forces to create appropriate technology for the third world. With varied objectives and extreme diversity in race, religion, class-status, and education, a team of unlikely heroes is born.', '2010-01-01', 0, 0.0, '', 0.0, 0);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Pets on a Train', N'When a train unexpectedly starts up, taking only pets with it, the animals discover that Hans, a badger with a grudge is behind it all. While the crash seems inevitable, the animals can count on Falcon, a roguish Raccoon who will do anything to save them.', '2025-07-02', 26, 3.4, 'https://image.tmdb.org/t/p/w500/xSibLTRfsUQagQnbOQLjp5oGbcq.jpg', 5.1, 87);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Girl Play', N'Two real-life lesbian actresses meet by chance when they are cast as lovers in a local stage play, and end up actually falling in love. Robin, who is married to her girlfriend for half a dozen years, and Lacie, someone who never had a lasting relationship, are both cast to play lesbian lovers in a Los Angeles stage play. Innocently, the stage director, Gabriel runs the actresses through a series of rehearsals designed to "bring out the intimacy" in each performer. Soon the two women find themselves increasingly and undeniably attracted to each other and overcome with desire. They must ask themselves whether this relationship is manufactured, created for the sake of the "girl play", or is true love.', '2004-07-11', 30, 2.8, 'https://image.tmdb.org/t/p/w500/2ZS0H8ysSzD0d0k8zdO2jeM3kge.jpg', 4.2, 80);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'TRON: Ares', N'A highly sophisticated Program called Ares is sent from the digital world into the real world on a dangerous mission, marking humankind''s first encounter with A.I. beings.', '2025-10-08', 357, 3.1, 'https://image.tmdb.org/t/p/w500/chpWmskl3aKm1aTZqUHRCtviwPy.jpg', 4.65, 119);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Avengers: Age of Ultron', N'When Tony Stark tries to jumpstart a dormant peacekeeping program, things go awry and Earth’s Mightiest Heroes are put to the ultimate test as the fate of the planet hangs in the balance. As the villainous Ultron emerges, it is up to The Avengers to stop him from enacting his terrible plans, and soon uneasy alliances and unexpected action pave the way for an epic and unique global adventure.', '2015-04-22', 23822, 3.6, 'https://image.tmdb.org/t/p/w500/4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg', 5.4, 141);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Regretting You', N'Morgan Grant and her daughter Clara explore what''s left behind after a devastating accident reveals a shocking betrayal and forces them to confront family secrets, redefine love, and rediscover each other.', '2025-10-22', 45, 3.5, 'https://image.tmdb.org/t/p/w500/z4gVnxTaks3anTycwKjDmvQSuWt.jpg', 5.25, 116);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Wrong Turn', N'Chris crashes into a carload of other young people, and the group of stranded motorists is soon lost in the woods of West Virginia, where they''re hunted by three cannibalistic mountain men who are grossly disfigured by generations of inbreeding.', '2003-05-30', 2873, 3.2, 'https://image.tmdb.org/t/p/w500/7lyxwOg7SdGff79yKCQmJ3AKWSf.jpg', 4.8, 84);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Man of Steel', N'A young boy learns that he has extraordinary powers and is not of this earth. As a young man, he journeys to discover where he came from and what he was sent here to do. But the hero in him must emerge if he is to save the world from annihilation and become the symbol of hope for all mankind.', '2013-06-12', 15750, 3.3, 'https://image.tmdb.org/t/p/w500/8GFtkImmK0K1VaUChR0n9O61CFU.jpg', 4.95, 143);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Evangelion: 3.0+1.0 Thrice Upon a Time', N'In the aftermath of the Fourth Impact, stranded without their Evangelions, Shinji, Asuka and Rei find refuge in one of the rare pockets of humanity that still exist on the ruined planet Earth. There, each lives a life far different from their days as an Evangelion pilot. However, the danger to the world is far from over. A new impact is looming on the horizon—one that will prove to be the true end of Evangelion.', '2021-03-08', 881, 4.1, 'https://image.tmdb.org/t/p/w500/md5wZRRj8biHrGtyitgBZo7674t.jpg', 6.15, 155);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'How to Train Your Dragon: The Hidden World', N'As Hiccup fulfills his dream of creating a peaceful dragon utopia, Toothless’ discovery of an untamed, elusive mate draws the Night Fury away. When danger mounts at home and Hiccup’s reign as village chief is tested, both dragon and rider must make impossible decisions to save their kind.', '2019-01-03', 6847, 3.9, 'https://image.tmdb.org/t/p/w500/xvx4Yhf0DVH8G4LzNISpMfFBDy2.jpg', 5.85, 104);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Mission: Impossible - The Final Reckoning', N'Ethan Hunt and team continue their search for the terrifying AI known as the Entity — which has infiltrated intelligence networks all over the globe — with the world''s governments and a mysterious ghost from Hunt''s past on their trail. Joined by new allies and armed with the means to shut the Entity down for good, Hunt is in a race against time to prevent the world as we know it from changing forever.', '2025-05-17', 2043, 3.6, 'https://image.tmdb.org/t/p/w500/z53D72EAOxGRqdr7KXXWp9dJiDe.jpg', 5.4, 170);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Kelly + Victor', N'When Kelly meets Victor on the dance floor of a Liverpool nightclub, the attraction is instant. After wandering through the night they find themselves at her flat, making love with a passion and urgency that neither had experienced before. Both Kelly and Victor are struggling to get by as best they can, while the people around them are choosing illegal lifestyles; she is escaping a brutish former lover, while he is being dragged into a world of drugs. It''s when they make love that their darker instincts take over.', '2012-10-16', 32, 2.7, 'https://image.tmdb.org/t/p/w500/qLi6TrmPgubYlc9OBek9wWMPfDr.jpg', 4.05, 95);       
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Jujutsu Kaisen 0', N'Yuta Okkotsu is a nervous high school student who is suffering from a serious problem—his childhood friend Rika has turned into a curse and won''t leave him alone. Since Rika is no ordinary curse, his plight is noticed by Satoru Gojo, a teacher at Jujutsu High, a school where fledgling exorcists learn how to combat curses. Gojo convinces Yuta to enroll, but can he learn enough in time to confront the curse that haunts him?', '2021-12-24', 1571, 4.1, 'https://image.tmdb.org/t/p/w500/23oJaeBh0FDk2mQ2P240PU9Xxfh.jpg', 6.15, 105);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Superman', N'Superman, a journalist in Metropolis, embarks on a journey to reconcile his Kryptonian heritage with his human upbringing as Clark Kent.', '2025-07-09', 3736, 3.7, 'https://image.tmdb.org/t/p/w500/wPLysNDLffQLOVebZQCbXJEv6E6.jpg', 5.55, 130);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Spectre', N'A cryptic message from Bond’s past sends him on a trail to uncover a sinister organization. While M battles political forces to keep the secret service alive, Bond peels back the layers of deceit to reveal the terrible truth behind SPECTRE.', '2015-10-26', 10897, 3.3, 'https://image.tmdb.org/t/p/w500/zj8ongFhtWNsVlfjOGo8pSr7PQg.jpg', 4.95, 148);

INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Crouching Tiger, Hidden Dragon', N'Two warriors in pursuit of a stolen sword and a notorious fugitive are led to an impetuous, physically-skilled, teenage nobleman''s daughter, who is at a crossroads in her life.', '2000-07-06', 3407, 3.7, 'https://image.tmdb.org/t/p/w500/iNDVBFNz4XyYzM9Lwip6atSTFqf.jpg', 5.55, 120);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Saw II', N'The chilling and relentless Jigsaw killer returns to terrorize the city once again. When a gruesome murder victim emerges with unmistakable traces of Jigsaw''s sinister methods, Detective Eric Matthews is thrust into a high-stakes investigation. To his surprise, apprehending Jigsaw seems almost too easy, but what he doesn''t realize is that being caught is merely another piece of Jigsaw''s intricate puzzle.', '2005-10-28', 5659, 3.3, 'https://image.tmdb.org/t/p/w500/gTnaTysN8HsvVQqTRUh8m35mmUA.jpg', 4.95, 93);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Hidden Face', N'Su-yeon, a cellist in an orchestra led by her fiancé and conductor Sung-jin, disappears one day, leaving behind only a video recording. Sung-jin is devastated over the loss of Su-yeon, but feels a strong attraction to Mi-ju, a cellist who fills in for his fiancée. Then one rainy night, Sung-jin and Mi-ju get swept away by their mutual desires for each other and commit an unforgivable act at Su-yeon’s house. Meanwhile, Su-yeon, who is thought to have gone missing, remains trapped in a secret room inside her house, and watches the naked truth unravel before her.', '2024-11-20', 46, 2.3, 'https://image.tmdb.org/t/p/w500/slRaAeEWbU8gM834X10qNhBhVIv.jpg', 3.45, 113);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Dumb and Dumber', N'Lloyd and Harry are two men whose stupidity is really indescribable. When Mary, a beautiful woman, loses an important suitcase with money before she leaves for Aspen, the two friends (who have found the suitcase) decide to return it to her. After some "adventures" they finally get to Aspen where, using the lost money they live it up and fight for Mary''s heart.', '1994-12-16', 6432, 3.3, 'https://image.tmdb.org/t/p/w500/4LdpBXiCyGKkR8FGHgjKlphrfUc.jpg', 4.95, 107);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Chernobyl: Abyss', N'The aftermath of a shocking explosion at the Chernobyl nuclear power station made hundreds of people sacrifice their lives to clean up the site of the catastrophe and to successfully prevent an even bigger disaster that could have turned a large part of the European continent into an uninhabitable exclusion zone. This is their story.', '2021-04-15', 548, 3.1, 'https://image.tmdb.org/t/p/w500/AmJLuHjxPdIJO6vmymeWADG6jK5.jpg', 4.65, 136);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Evangelion: 2.0 You Can (Not) Advance', N'Under constant attack by monstrous creatures called Angels that seek to eradicate humankind, U.N. Special Agency NERV introduces two new EVA pilots to help defend the city of Tokyo-3: the mysterious Makinami Mari Illustrous and the intense Asuka Langley Shikinami. Meanwhile, Gendo Ikari and SEELE proceed with a secret project that involves both Rei and Shinji.', '2009-06-26', 940, 3.9, 'https://image.tmdb.org/t/p/w500/7VLYN2CfJpB6PrcuzDKKqdGSUi6.jpg', 5.85, 112);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Cold Fish', N'Shamoto runs a small tropical fish shop. When his daughter Mitsuko is caught shoplifting at a grocery store a man named Murata steps in to settle things between the girl and the store manager. Murata also runs a tropical fish shop and he and Shamoto soon become friendly. However Murata hides many dark secrets behind his friendly face.', '2011-01-29', 372, 3.5, 'https://image.tmdb.org/t/p/w500/669GmEZsyMlPliURX5myHTStslv.jpg', 5.25, 146);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Dr. No', N'Agent 007 battles mysterious Dr. No, a scientific genius bent on destroying the U.S. space program. As the countdown to disaster begins, Bond must go to Jamaica, where he encounters beautiful Honey Ryder, to confront a megalomaniacal villain in his massive island headquarters.', '1962-10-07', 3856, 3.5, 'https://image.tmdb.org/t/p/w500/9zCOLJmLNst0sCPZlkW1IRoH65E.jpg', 5.25, 110);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Antiporno', N'Young artist Kyoko wreaks havoc on everyone that she encounters when Japan''s oldest major movie studio asks a batch of venerable filmmakers to revive its high-brow soft-core Roman Porno series.', '2017-01-28', 423, 3.3, 'https://image.tmdb.org/t/p/w500/1hL1OlEHPuqZAK2QXR8tCHCGMZR.jpg', 4.95, 76);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Skin I Live In', N'A brilliant plastic surgeon creates a synthetic skin that withstands any kind of damage. His guinea pig: a mysterious and volatile woman who holds the key to his obsession.', '2011-08-17', 4452, 3.7, 'https://image.tmdb.org/t/p/w500/xa7uCwGYykrf8MMI8iF5dZvNlrG.jpg', 5.55, 120);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'It''s a Wonderful Life', N'A holiday favourite for generations...  George Bailey has spent his entire life giving to the people of Bedford Falls.  All that prevents rich skinflint Mr. Potter from taking over the entire town is George''s modest building and loan company.  But on Christmas Eve the business''s $8,000 is lost and George''s troubles begin.', '1946-12-20', 4631, 4.1, 'https://image.tmdb.org/t/p/w500/bSqt9rhDZx1Q7UZ86dBPKdNomp2.jpg', 6.15, 130);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Audition', N'Seven years after the death of his wife, widower Shigeharu seeks advice on how to find a new wife from a colleague. Taking advantage of their position as a film company, they stage an audition. Interviewing a series of women, Shigeharu is enchanted by the quiet Asami. But soon things take a twisted turn as Asami isn’t what she seems to be.', '2000-03-03', 1671, 3.6, 'https://image.tmdb.org/t/p/w500/zwGaUMm0wAqi0wkO7LJDlwoA5LP.jpg', 5.4, 115);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Fantastic Beasts: The Secrets of Dumbledore', N'Professor Albus Dumbledore knows the powerful, dark wizard Gellert Grindelwald is moving to seize control of the wizarding world. Unable to stop him alone, he entrusts magizoologist Newt Scamander to lead an intrepid team of wizards and witches. They soon encounter an array of old and new beasts as they clash with Grindelwald''s growing legion of followers.', '2022-04-06', 4875, 3.3, 'https://image.tmdb.org/t/p/w500/3c5GNLB4yRSLBby0trHoA1DSQxQ.jpg', 4.95, 142);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Evangelion: 3.0 You Can (Not) Redo', N'Fourteen years after Third Impact, Shinji Ikari awakens to a world he does not remember. He hasn''t aged. Much of Earth is laid in ruins, NERV has been dismantled, and people who he once protected have turned against him. Befriending the enigmatic Kaworu Nagisa, Shinji continues the fight against the angels and realizes the fighting is far from over, even when it could be against his former allies. The characters'' struggles continue amidst the battles against the angels and each other, spiraling down to what could inevitably be the end of the world.', '2012-11-17', 877, 3.6, 'https://image.tmdb.org/t/p/w500/d0s1xvykzl0kz7fP5S2ROYqphdz.jpg', 5.4, 96);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Muzzle', N'LAPD K-9 officer Jake Rosser has just witnessed the shocking murder of his dedicated partner by a mysterious assailant. As he investigates the shooter’s identity, he uncovers a vast conspiracy that has a choke-hold on the city in this thrilling journey through the tangled streets of Los Angeles and the corrupt bureaucracy of the LAPD.', '2023-09-29', 311, 3.2, 'https://image.tmdb.org/t/p/w500/cDRtayyKphw2HHW3KBRwPIEhY44.jpg', 4.8, 100);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Dumbo', N'A young elephant, whose oversized ears enable him to fly, helps save a struggling circus, but when the circus plans a new venture, Dumbo and his friends discover dark secrets beneath its shiny veneer.', '2019-03-27', 4446, 3.3, 'https://image.tmdb.org/t/p/w500/qgibOIN9RDHiPdimw7Gc7YcY960.jpg', 4.95, 112);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Army of Shadows', N'Betrayed by an informant, Philippe Gerbier finds himself trapped in a torturous Nazi prison camp. Though Gerbier escapes to rejoin the Resistance in occupied Marseilles, France, and exacts his revenge on the informant, he must continue a quiet, seemingly endless battle against the Nazis in an atmosphere of tension, paranoia and distrust.', '1969-09-10', 698, 4.0, 'https://image.tmdb.org/t/p/w500/aqNZWM9bspt8zaDvVRIRiWxRVJ7.jpg', 6.0, 145);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Captain Avispa', N'In Avispatropolis, the fearless Captain Avispa emerges as an exemplary protector of the city, whose courage and convictions always prevail over the forces of evil. His unbreakable power is nourished by absolute sincerity, as he would lose his strength if he dared to weave deceit. Only in pursuit of noble causes does he allow himself to deviate from the truth. As is common in stories of this kind, Captain Wasp is surrounded by a constellation of close friends and arch-enemies, whose stories have their origins in the artist''s songs.', '2024-04-04', 39, 3.5, 'https://image.tmdb.org/t/p/w500/zmthz3CuFljmBQcfuaz4hBNwbQ0.jpg', 5.25, 88);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Thunderball', N'A criminal organization has obtained two nuclear bombs and are asking for a 100 million pound ransom in the form of diamonds in seven days or they will use the weapons. The secret service sends James Bond to the Bahamas to once again save the world.', '1965-12-11', 2491, 3.3, 'https://image.tmdb.org/t/p/w500/wCc4qllaTDsQN8zgGkAgQrKO6N9.jpg', 4.95, 130);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Absolution', N'An aging ex-boxer gangster working as muscle for a Boston crime boss receives an upsetting diagnosis.  Despite a faltering memory, he attempts to rectify the sins of his past and reconnect with his estranged children. He is determined to leave a positive legacy for his grandson, but the criminal underworld isn’t done with him and won’t loosen their grip willingly.', '2024-10-31', 473, 2.9, 'https://image.tmdb.org/t/p/w500/gt70JOD9xsPlpJnuBJAWdOT4yRg.jpg', 4.35, 112);

INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Josee, the Tiger and the Fish', N'With dreams of diving abroad, Tsuneo gets a job assisting Josee, an artist whose imagination takes her far beyond her wheelchair. But when the tide turns against them, they push each other to places they never thought possible, and inspire a love fit for a storybook.', '2020-12-25', 547, 4.1, 'https://image.tmdb.org/t/p/w500/z1D8xi9x4uEhyFruo7uEHXUMD4K.jpg', 6.15, 98);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Hunchback of Notre Dame', N'Isolated bell-ringer Quasimodo wishes to leave Notre Dame tower against the wishes of Judge Claude Frollo, his stern guardian and Paris'' strait-laced Minister of Justice. His first venture to the outside world finds him Esmeralda, a kind-hearted and fearless Romani woman who openly stands up to Frollo''s tyranny.', '1996-06-21', 5213, 3.6, 'https://image.tmdb.org/t/p/w500/hImMgT9B27evYSRmfztqdDtX6qi.jpg', 5.4, 91);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Quantum of Solace', N'Betrayed by Vesper, the woman he loved, 007 fights the urge to make his latest mission personal. Pursuing his determination to uncover the truth, Bond and M interrogate Mr. White, who reveals that the organization that blackmailed Vesper is far more complex and dangerous than anyone had imagined.', '2008-10-29', 8210, 3.2, 'https://image.tmdb.org/t/p/w500/e3DXXLJHGqMx9yYpXsql1XNljmM.jpg', 4.8, 106);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'What Women Want', N'Advertising executive Nick Marshall is as cocky as they come, but what happens to a chauvinistic guy when he can suddenly hear what women are thinking? Nick gets passed over for a promotion, but after an accident enables him to hear women''s thoughts, he puts his newfound talent to work against Darcy, his new boss, who seems to be infatuated with him.', '2000-12-15', 4152, 3.2, 'https://image.tmdb.org/t/p/w500/eqkBEMDk1316Yx5wVoabWY07JAi.jpg', 4.8, 127);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Gardener', N'Every year the Prime Minister has a list of all kinds of troublemakers eliminated in the name of the famous Reason of State. Serge Shuster, Special Adviser to the President of the Republic, finds himself on this list, better known as the Matignon List.  Condemned to certain death and at the heart of an implacable plot and a state secret that also put his family in danger, Serge, his wife and children have only one hope left - their gardener, Léo, who hates it when « slugs » invade his garden... Especially those that want to kill innocent families.', '2025-01-30', 168, 3.1, 'https://image.tmdb.org/t/p/w500/5T9WR7vIOnHm6xhVt5zBuPbBgt1.jpg', 4.65, 110);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Happy Feet', N'Into the world of the Emperor Penguins, who find their soul mates through song, a penguin is born who cannot sing. But he can tap dance something fierce!', '2006-11-16', 5300, 3.1, 'https://image.tmdb.org/t/p/w500/za41IHkj6LnkilfTzv5B2qmthKD.jpg', 4.65, 108);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Antique', N'Jin-hyeok opens a cake shop in an old antique shop, hiring Seon-woo, Korea''s best pastry chef, who fell in love with him in high school. Also there, are Su-young, crushing on Seon-woo, ex-boxer Ki-beom, and Seon-woo''s French ex-boyfriend.', '2008-11-13', 64, 3.1, 'https://image.tmdb.org/t/p/w500/wtjJAFaHL5GEzOzHZaCKI9TjyN6.jpg', 4.65, 111);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'On Her Majesty''s Secret Service', N'James Bond tracks his archnemesis, Ernst Blofeld, to a mountaintop retreat in the Swiss alps where he is training an army of beautiful, lethal women. Along the way, Bond falls for Italian contessa Tracy Draco, and marries her in order to get closer to Blofeld.', '1969-12-18', 2023, 3.3, 'https://image.tmdb.org/t/p/w500/m3KfbxvqaiAvRJ6MpguA3GuLdDQ.jpg', 4.95, 142);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Taking of Deborah Logan', N'What starts as a poignant medical documentary about Deborah Logan''s descent into Alzheimer''s disease and her daughter''s struggles as caregiver degenerates into a maddening portrayal of dementia at its most frightening, as hair-raising events begin to plague the family and crew and an unspeakable malevolence threatens to tear the very fabric of sanity from them all.', '2014-10-21', 1386, 3.2, 'https://image.tmdb.org/t/p/w500/77i7EBUyQKOUiZeYQ5tWDGQb0AI.jpg', 4.8, 90);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Copshop', N'On the run from a lethal assassin, a wily con artist devises a scheme to hide out inside a small-town police station. However, when the hit man turns up at the precinct, an unsuspecting rookie cop finds herself caught in the crosshairs.', '2021-09-09', 843, 3.1, 'https://image.tmdb.org/t/p/w500/9LEWWWEhS7SZXFDuH1YYhs0VFct.jpg', 4.65, 108);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'A View to a Kill', N'A newly-developed microchip designed by Zorin Industries for the British Government that can survive the electromagnetic radiation caused by a nuclear explosion has landed in the hands of the KGB. James Bond must find out how and why. His suspicions soon lead him to big industry leader Max Zorin who forms a plan to destroy his only competition in Silicon Valley by triggering a massive earthquake in the San Francisco Bay.', '1985-05-24', 2091, 3.1, 'https://image.tmdb.org/t/p/w500/arJF829RP9cYvh0NU70dC5TtXSa.jpg', 4.65, 131);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Jurassic World Rebirth', N'Five years after the events of Jurassic World Dominion, covert operations expert Zora Bennett is contracted to lead a skilled team on a top-secret mission to secure genetic material from the world''s three most massive dinosaurs. When Zora''s operation intersects with a civilian family whose boating expedition was capsized, they all find themselves stranded on an island where they come face-to-face with a sinister, shocking discovery that''s been hidden from the world for decades.', '2025-07-01', 2424, 3.2, 'https://image.tmdb.org/t/p/w500/1RICxzeoNCAO5NpcRMIgg1XT6fm.jpg', 4.8, 134);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Licence to Kill', N'After capturing the notorious drug lord Franz Sanchez, Bond''s close friend and former CIA agent Felix Leiter is left for dead and his wife is murdered. Bond goes rogue and seeks vengeance on those responsible, as he infiltrates Sanchez''s organization from the inside.', '1989-06-13', 2049, 3.2, 'https://image.tmdb.org/t/p/w500/8nzJve63EXA79HGAyidZwivZrQ2.jpg', 4.8, 133);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Onoda: 10,000 Nights in the Jungle', N'Japan, 1944. Trained for intelligence work, Hiroo Onoda, 22 years old, discovers a philosophy contrary to the official line: no suicide; stay alive whatever happens; the mission is more important than anything else. Sent to Lubang, a small island in the Philippines where the Americans are about to land, this role will be to wage a guerrilla war until the return of the Japanese troops. The Empire will surrender soon after; Onoda, 10,000 days later.', '2021-07-21', 150, 3.6, 'https://image.tmdb.org/t/p/w500/tKzFwiEm86AVRsefgqODTBjjh98.jpg', 5.4, 167);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Shadow Strays', N'Skilled in the art of killing, a young assassin defies her mentor to save a boy from a ruthless crime syndicate — and she''ll destroy anyone in her path.', '2024-09-10', 283, 3.6, 'https://image.tmdb.org/t/p/w500/cfkcrKySRyJiIdLo6c6kNSyLFh7.jpg', 5.4, 145);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Duma', N'An orphaned cheetah becomes the best friend and pet of a young boy living in South Africa.', '2005-04-22', 200, 3.6, 'https://image.tmdb.org/t/p/w500/opoDxQW9S6SaiP8rY7urw16QVTL.jpg', 5.4, 100);    
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Garden of Sinners: Paradox Spiral', N'Tomoe Enjou is attacked by bullies from his old school and saved by Shiki Ryougi. He asks her to hide him at her place and admits that he killed someone. Several days later, there are still no broadcasts about the murder as if it didn''t happen... and when the victims are found, they''re alive and unharmed.', '2008-08-16', 102, 3.8, 'https://image.tmdb.org/t/p/w500/vScnbrMbDpuwbiRafOcuxHjDKsI.jpg', 5.7, 114);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Women', N'Liang Pao-erh joins the carefree Spinsters'' Club when she discovers her husband is having an affair. Despite the seemingly happy front that her sisters put on, beneath it all, each of them secretly yearns for a man in her life.', '1985-06-12', 8, 3.3, 'https://image.tmdb.org/t/p/w500/i9jPlphJJM34QrGKi9MjI3jyA8T.jpg', 4.95, 90);
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'Martyrs', N'A woman and her childhood friend seek out revenge on those who victimized and abused them.', '2015-10-09', 317, 2.6, 'https://image.tmdb.org/t/p/w500/pkBWgdlFClVrr39iLpUTdzqvgz8.jpg', 3.9, 86);  
INSERT INTO movie (title, description, release_date, raterCount, rating, poster_url, price, duration)
    VALUES (N'The Garden of Sinners: Remaining Sense of Pain', N'July 1998 - After a group of delinquents is found dead in their hangout place with all their limbs twisted and torn off, Aozaki Touko receives a request to find the murderer and asks Shiki for help. The main suspect is Asagami Fujino; a girl who was the boys'' plaything until recently, who Shiki believes to be "one of her kind".', '2008-02-09', 113, 3.5, 'https://image.tmdb.org/t/p/w500/3TeeCstvdqb6E72dMPEb43rCD0U.jpg', 5.25, 58);

-- DELETE FROM movie
-- DBCC CHECKIDENT ('dbo.movie', RESEED, 0);